### PR TITLE
Messages

### PR DESCRIPTION
**Pull request by MineKing9534**
## Checklist

 - [x] Read [Contribution Guidelines](https://github.com/SlimeCloud/java-SlimeBot#-contributing) and [Style Guides](https://github.com/SlimeCloud/java-SlimeBot#-style-guide)
 - [x] Test the Code
 - [x] This PR is ready to review and merge

## Description
Add command to send messages as bot from a file

## Note
We will have to do some migration to the config:
```
...
guildStorage: "guild/%guild%"
...
```
instead of 
```
...
guildStorage: "guild/%guild%.json"
...
```

And for the folder structure:
```
guild
- GuildID
  - config.json
```
instead of 
```
guild
- GuildID.json
```

(The guild/%guildid% folder will now hold general resource files. In this case we added messages)

### CODE REVIEW

**Comment by MatitoDev** [comment]
What do we need the feature for?

**Comment by MineKing9534** [comment]
We (Nana and I) are planning to use this to send the server rules, faq and server guide

**Comment by MatitoDev** [comment]
> We (Nana and I) are planning to use this to send the server rules, faq and server guide

ah true i remember

**Review by MatitoDev — APPROVED** [review]
seems to work

**Pull request merged**
